version: '3.5'
services:
  api1: # API - Instância 01
    image: api
    hostname: api1
    container_name: rinha_api1
    network_mode: "host"
    environment:
      API_PORT: 5000
      USE_HOST: "1"
    build: ./
    depends_on:
      - db
#    ports:
#      - "5000:5000"
#    expose:
#      - "5000"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M

  api2: # API - Instância 02
    image: api
    hostname: api2
    container_name: rinha_api2
    network_mode: "host"
    environment:
      API_PORT: 5001
      USE_HOST: "1"
    build: ./
    depends_on:
      - db
#    ports:
#      - "5001:5001"
#    expose:
#      - "5001"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M

  nginx: # Load Balancer
    image: nginx:latest
    container_name: rinha_nginx
    network_mode: "host"
    volumes:
      - ./devops/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
#    expose:
#      - "9999"
    # ports:
    #   - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1000M

  db: # Banco de dados
   image: postgres
#   ports:
#     - "5432:5432"
   environment:
     POSTGRES_DB: "rinha"
     POSTGRES_USER: "rinha"
     POSTGRES_PASSWORD: "rinha"
   hostname: postgres
   network_mode: "host"
   container_name: rinha_postgres
   volumes:
     - ./devops/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
   deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1000M

