version: '3.5'
services:
  api1: # API - Instância 01
    image: api
    hostname: api1
    container_name: rinha_api1
    build: ./
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M

  api2: # API - Instância 02
    image: api
    hostname: api2
    container_name: rinha_api2
    build: ./
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M

  nginx: # Load Balancer
    image: nginx:latest
    container_name: rinha_nginx
    volumes:
      - ./devops/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M

  db: # Banco de dados
   image: postgres
   ports:
     - "5432:5432"
   environment:
     POSTGRES_DB: "rinha"
     POSTGRES_USER: "rinha"
     POSTGRES_PASSWORD: "rinha"
   hostname: postgres
   container_name: rinha_postgres
   volumes:
     - ./devops/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
   deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1500M

